### ISSUE TITLE
Update for Python3

### ISSUE THREAD

**Issue by Phr3d13** [marian42/pixelpi#4]
Is there any way we can get a group effort kinda thing going on to get this updated to run on Python3? I've made some headway, but am currently stuck with this error:
Traceback (most recent call last):
```
  File "menu.py", line 154, in <module>
    menu = Menu(create_screen(), create_menu_items())
  File "/home/pi/pixelpi/screenfactory.py", line 9, in create_screen
    return Screen()
  File "/home/pi/pixelpi/screen/screen.py", line 12, in __init__
    self.strip = neopixel.NeoPixel(width * height, led_pin, led_freq_hz, led_dma, led_invert, led_brightness)
TypeError: __init__() takes 3 positional arguments but 7 were given
```
I can upload my changes if needed/wanted.

**Comment by marian42** [comment]
This error looks like the API of Neopixel has changed. To address that, you might want to get an example with neopixel running and compare the constructor parameters that it takes.

Did you get the project to run with Python 2?

Unfortunately, I currently don't have the resources to help moving this project to Python 3, but I'll happily merge a PR that does it.
